package org.intellij.sdk.language.psi;

import com.intellij.psi.PsiNameIdentifierOwner;

/**
 * PSI interface for a Harbour PROCEDURE declaration.
 * Usually generated by GrammarKit from your BNF rule:
 *
 *     procedure_declaration ::=
 *         PROCEDURE IDENT statement_block ENDPROCEDURE?
 */
public interface HarbourProcedureDeclaration extends PsiNameIdentifierOwner {
}
